"""
Generate RESULTS.md — one page containing every number in the submission,
each traced to the file that produced it.

Written as a script rather than a hand-maintained document because these
numbers were re-measured many times (model changes, a rate-limited provider,
a workspace that idled out mid-run, bug fixes that shifted accuracy). Every
hand-copied figure is a chance to publish a stale one, and this benchmark has
already had one figure quoted from a run whose failed rows were excluded from
the denominator.

    python -m scripts.make_report
"""
import json
import os
import sys
from datetime import date

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import config

PIPES = [("rag", "RAG"), ("graphrag", "GraphRAG"), ("agentic_graphrag", "Agentic GraphRAG")]

# (suffix, heading, what this run is for)
#
# These are the suffixes of the CURRENT sweep. They were once the suffixes of
# an older one, and because a missing summary was silently skipped, the report
# kept regenerating happily from whatever stale files still matched: a chained
# section from a run three weeks old, a provided section measured with a TF-IDF
# embedder, and a hidden section produced by a different model entirely, all
# presented side by side as one result. Both guards below exist so that cannot
# happen again -- a missing run is now an error, and sections that disagree
# about the model, embedder or backend are an error.
RUNS = [
    ("_v2_provided", "Provided set (100) — controlled comparison",
     "Every pipeline compiles its query with the same LLM, so all three spend "
     "real tokens. This is the configuration that answers *does adaptivity help*."),
    ("_v2_chained", "Chained set (60) — controlled comparison",
     "Questions whose subject must be resolved before it can be queried. A fixed "
     "pipeline cannot express these at any model quality."),
    ("_v2_fastpath", "Provided set (100) — production configuration",
     "The regex fast path enabled, as you would deploy it. This is the "
     "configuration that answers *how well does the system work*."),
    ("_hidden_final", "Hidden set (50) — submission",
     "No gold answers; raw outputs, token counts and full agentic traces."),
]


def _load(suffix):
    p = os.path.join(config.OUTPUT_DIR, f"summary{suffix}.json")
    if not os.path.exists(p):
        return None
    with open(p, encoding="utf-8") as f:
        return json.load(f)


def _fmt(v, nd=3):
    if v is None:
        return "—"
    if isinstance(v, float):
        return f"{v:.{nd}f}"
    if isinstance(v, int) and v > 999:
        return f"{v:,}"
    return str(v)


def main():
    out = [
        "# Results",
        "",
        "Every number here is generated by `python -m scripts.make_report` from the "
        "JSON in `outputs/`, so it cannot drift from what the benchmark actually "
        "produced. Regenerate after any run.",
        "",
        f"_Generated {date.today().isoformat()}._",
        "",
    ]

    missing = [sfx for sfx, _, _ in RUNS if _load(sfx) is None]
    if missing:
        sys.exit("refusing to write a partial report — no summary for: "
                 + ", ".join(missing)
                 + ". Run the sweep for these before reporting.")

    # Every section has to describe the SAME system, or the table compares runs
    # rather than pipelines.
    configs = {}
    for sfx, _, _ in RUNS:
        mm = _load(sfx).get("_meta", {})
        configs[sfx] = (mm.get("graph_backend"), mm.get("llm_model"), mm.get("embedder"))
    if len(set(configs.values())) > 1:
        detail = [f"  summary{k}.json  backend={v[0]} model={v[1]} embedder={v[2]}"
                  for k, v in configs.items()]
        sys.exit("refusing to write a report mixing configurations:"
                 + chr(10) + chr(10).join(detail))

    for suffix, heading, blurb in RUNS:
        s = _load(suffix)
        m = s.get("_meta", {})
        out += [f"## {heading}", "", blurb, "",
                f"`summary{suffix}.json` · backend **{m.get('graph_backend','?')}** · "
                f"model **{m.get('llm_model','?')}** · "
                f"regex fast path **{m.get('regex_fast_path', 'n/a')}** · "
                f"embedder `{m.get('embedder','?')}`", ""]

        has_acc = any((s.get(k) or {}).get("exact_match_accuracy") is not None
                      for k, _ in PIPES)
        if has_acc:
            out += ["| Pipeline | Accuracy | Avg tokens | Tokens / correct | LLM calls | Answered |",
                    "|---|---|---|---|---|---|"]
        else:
            out += ["| Pipeline | Avg tokens | LLM calls | Answered |", "|---|---|---|---|"]

        for key, label in PIPES:
            d = s.get(key) or {}
            if not d.get("n_questions"):
                continue
            if has_acc:
                out.append(
                    f"| {label} | **{_fmt(d.get('exact_match_accuracy'))}** | "
                    f"{_fmt(d.get('avg_tokens'), 0)} | "
                    f"{_fmt(d.get('tokens_per_correct_answer'), 0)} | "
                    f"{_fmt(d.get('avg_llm_calls'), 2)} | {_fmt(d.get('answered_rate'))} |")
            else:
                out.append(f"| {label} | {_fmt(d.get('avg_tokens'), 0)} | "
                           f"{_fmt(d.get('avg_llm_calls'), 2)} | {_fmt(d.get('answered_rate'))} |")
        out.append("")

        b = s.get("agentic_behavior")
        if b:
            out += [f"Escalation **{b['escalation_rate']:.1%}** "
                    f"({b['n_escalated']} escalated / {b['n_resolved_free']} resolved without "
                    f"reasoning) · avg {b['avg_citations']} citations · "
                    f"{b['avg_strategy_changes']} strategy changes", "",
                    "Methods the agent selected: "
                    + ", ".join(f"`{k}`×{v}" for k, v in b["retrieval_methods_used"].items()),
                    ""]

        va = s.get("agentic_value_by_qtype")
        if va:
            out += ["| Question type | n | RAG | GraphRAG | Agentic | Verdict |",
                    "|---|---|---|---|---|---|"]
            for qt, e in va.items():
                a = e["accuracy"]
                out.append(f"| `{qt}` | {e['n']} | {_fmt(a.get('rag'), 2)} | "
                           f"{_fmt(a.get('graphrag'), 2)} | **{_fmt(a.get('agentic_graphrag'), 2)}** | "
                           f"{e.get('verdict', '—')} |")
            out.append("")

    out += [
        "## Reproducing",
        "",
        "```bash",
        "python -m scripts.setup_tigergraph      # schema, queries, load, verify",
        "python -m src.eval.stress_set --n 60    # regenerate the chained set",
        "python -m src.eval.run_benchmark                  # controlled comparison",
        "python -m src.eval.run_benchmark --stress",
        "python -m src.eval.run_benchmark --fast-path      # production configuration",
        "python -m src.eval.run_benchmark --hidden --pipelines graphrag,agentic_graphrag",
        "python -m scripts.make_report           # regenerate this file",
        "```",
        "",
        "## Reading these numbers honestly",
        "",
        "**Two configurations, two different questions.** The production configuration "
        "answers *how well does the system work*. The controlled comparison handicaps "
        "every pipeline onto the same LLM compiler and answers *does adaptivity help* — "
        "absolute accuracy is low there for all three because an 8B model is a poor "
        "NL→query compiler, which is the variable under test.",
        "",
        "**Cost per correct answer, not cost per question.** A pipeline that is cheap "
        "because it declines to answer is not efficient. On the chained set the agent "
        "is both the most accurate and the cheapest per correct answer.",
        "",
        "**Negative results are included.** Two chained families are not solved at "
        "all. `chained_venue` asks for a superlative scoped by venue, which the "
        "query schema cannot express — `superlative` takes a discipline and an "
        "edition, not a venue — so the agent answers from the wrong scope. "
        "`chained_chronology` identifies an edition by its host city, and nothing "
        "resolves a city to a Games. Both are schema gaps rather than reasoning "
        "failures, and neither is omitted here.",
        "",
        "**Errored questions count against the pipeline that errored.** A question "
        "whose run raised is a question that pipeline did not answer, so it stays in "
        "the denominator; `n_errors` in each summary records how many there were. "
        "Dropping them is how the chained set once read 0.500 instead of 0.483.",
        "",
    ]

    path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                        "RESULTS.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print(f"wrote {path} ({len(out)} lines)")


if __name__ == "__main__":
    main()
